In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from 'C:\\Users\\alidani\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [3]:
import pandas as pd

In [4]:
pd

<module 'pandas' from 'C:\\Users\\alidani\\anaconda3\\lib\\site-packages\\pandas\\__init__.py'>

In [5]:
df=pd.read_csv('data.csv')

In [6]:
len(df)

11914

df.head()

In [9]:
df.groupby('Make').MSRP.max()

Make
Acura             156000
Alfa Romeo         68400
Aston Martin      320695
Audi              199900
BMW               141200
Bentley           363000
Bugatti          2065902
Buick              49625
Cadillac          104215
Chevrolet          92395
Chrysler           49470
Dodge             120395
FIAT               31800
Ferrari           643330
Ford              149995
GMC                71665
Genesis            54550
HUMMER             43130
Honda              47070
Hyundai            68750
Infiniti           88850
Kia                61900
Lamborghini      1500000
Land Rover        199495
Lexus             375000
Lincoln            76650
Lotus              93225
Maserati          182009
Maybach          1382750
Mazda              44015
McLaren           280225
Mercedes-Benz     495000
Mitsubishi         38995
Nissan            149990
Oldsmobile         36795
Plymouth           44625
Pontiac            37610
Porsche           440000
Rolls-Royce       492425
Saab               5

In [13]:
df.groupby('Make').MSRP.mean()

Make
Acura            3.488759e+04
Alfa Romeo       6.160000e+04
Aston Martin     1.979104e+05
Audi             5.345211e+04
BMW              6.154676e+04
Bentley          2.471693e+05
Bugatti          1.757224e+06
Buick            2.820661e+04
Cadillac         5.623132e+04
Chevrolet        2.835039e+04
Chrysler         2.672296e+04
Dodge            2.239006e+04
FIAT             2.267024e+04
Ferrari          2.382188e+05
Ford             2.739927e+04
GMC              3.049330e+04
Genesis          4.661667e+04
HUMMER           3.646441e+04
Honda            2.667434e+04
Hyundai          2.459704e+04
Infiniti         4.239421e+04
Kia              2.531017e+04
Lamborghini      3.315673e+05
Land Rover       6.782322e+04
Lexus            4.754907e+04
Lincoln          4.283983e+04
Lotus            6.918828e+04
Maserati         1.142077e+05
Maybach          5.462219e+05
Mazda            2.003938e+04
McLaren          2.398050e+05
Mercedes-Benz    7.147623e+04
Mitsubishi       2.124054e+04
Nissa

In [15]:
df.groupby('Make').MSRP.mean().round(2)

Make
Acura              34887.59
Alfa Romeo         61600.00
Aston Martin      197910.38
Audi               53452.11
BMW                61546.76
Bentley           247169.32
Bugatti          1757223.67
Buick              28206.61
Cadillac           56231.32
Chevrolet          28350.39
Chrysler           26722.96
Dodge              22390.06
FIAT               22670.24
Ferrari           238218.84
Ford               27399.27
GMC                30493.30
Genesis            46616.67
HUMMER             36464.41
Honda              26674.34
Hyundai            24597.04
Infiniti           42394.21
Kia                25310.17
Lamborghini       331567.31
Land Rover         67823.22
Lexus              47549.07
Lincoln            42839.83
Lotus              69188.28
Maserati          114207.71
Maybach           546221.88
Mazda              20039.38
McLaren           239805.00
Mercedes-Benz      71476.23
Mitsubishi         21240.54
Nissan             28583.43
Oldsmobile         11542.54
Plymouth       

In [18]:
df.groupby('Year').MSRP.mean().round(2)

Year
1990     2020.20
1991     2080.66
1992     2077.74
1993     2187.33
1994     2312.03
1995     2606.78
1996     2497.37
1997     3105.21
1998     2975.60
1999     3096.16
2000     3166.67
2001    41500.67
2002    33744.16
2003    39774.06
2004    36107.34
2005    36746.97
2006    32056.47
2007    34974.19
2008    54138.92
2009    49838.56
2010    50642.50
2011    57548.18
2012    59516.24
2013    48698.50
2014    63226.36
2015    46794.46
2016    47220.74
2017    42191.53
Name: MSRP, dtype: float64

In [21]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [33]:

df.groupby('Year').MSRP.isnull()

AttributeError: 'SeriesGroupBy' object has no attribute 'isnull'

In [42]:
df.groupby('Year').('Number of Doors').mean()

SyntaxError: invalid syntax (<ipython-input-42-2aa4e059088f>, line 1)

In [43]:
df2=df[
    df['Year'] >= 2015
]


In [44]:
df2.head()

Make       Model  Year                Engine Fuel Type  Engine HP  \
32  FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
33  FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
34  FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
41   BMW    2 Series  2016     premium unleaded (required)      240.0   
42   BMW    2 Series  2016     premium unleaded (required)      240.0   

    Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
32               4.0            MANUAL  rear wheel drive              2.0   
33               4.0            MANUAL  rear wheel drive              2.0   
34               4.0            MANUAL  rear wheel drive              2.0   
41               4.0         AUTOMATIC  rear wheel drive              2.0   
42               4.0         AUTOMATIC  rear wheel drive              2.0   

       Market Category Vehicle Size Vehicle Style  highway MPG  city mpg  \
32         Performance      Compact   Convertible           35        26   
33         Performance      Compact   Convertible           35        26   
34         Performance      Compact   Convertible           35        26   
41  Luxury,Performance      Compact         Coupe           35        23   
42              Luxury      Compact   Convertible           34        23   

    Popularity   MSRP  
32         819  27495  
33         819  24995  
34         819  28195  
41        3916  32850  
42        3916  38650

In [45]:
df2.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        0
Engine HP              51
Engine Cylinders        8
Transmission Type       0
Driven_Wheels           0
Number of Doors         5
Market Category      1324
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [64]:
a=df['Engine HP'].mean()
a=round(a)
a

249

In [49]:
df['Engine HP'].fillna(249.38)

0        335.0
1        300.0
2        300.0
3        230.0
4        230.0
         ...  
11909    300.0
11910    300.0
11911    300.0
11912    300.0
11913    221.0
Name: Engine HP, Length: 11914, dtype: float64

In [50]:
df['Engine HP'].mean()

249.38607007176023

In [51]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [52]:
values ={"Engine HP": 249.38}

In [55]:
df.fillna(value=values)
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [54]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [56]:
df['Engine HP'].mean()

249.38607007176023

In [57]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [58]:
df['Engine HP'].fillna(249.38, inplace = True)

In [59]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP               0
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [60]:
df['Engine HP'].mean()

249.38603491690392

In [65]:
a=df['Engine HP'].mean()
a=round(a)
a

249

In [66]:
df3=df[
    df['Make'] == 'Rolls-Royce'
]

In [67]:
df3.head()

Make            Model  Year             Engine Fuel Type  \
2921  Rolls-Royce         Corniche  2001  premium unleaded (required)   
3505  Rolls-Royce             Dawn  2016  premium unleaded (required)   
5275  Rolls-Royce  Ghost Series II  2015  premium unleaded (required)   
5276  Rolls-Royce  Ghost Series II  2015  premium unleaded (required)   
5277  Rolls-Royce  Ghost Series II  2016  premium unleaded (required)   

      Engine HP  Engine Cylinders Transmission Type     Driven_Wheels  \
2921      325.0               8.0         AUTOMATIC  rear wheel drive   
3505      563.0              12.0         AUTOMATIC  rear wheel drive   
5275      563.0              12.0         AUTOMATIC  rear wheel drive   
5276      563.0              12.0         AUTOMATIC  rear wheel drive   
5277      563.0              12.0         AUTOMATIC  rear wheel drive   

      Number of Doors                 Market Category Vehicle Size  \
2921              2.0                   Exotic,Luxury        Large   
3505              2.0  Exotic,Luxury,High-Performance        Large   
5275              4.0       Exotic,Luxury,Performance        Large   
5276              4.0       Exotic,Luxury,Performance        Large   
5277              4.0       Exotic,Luxury,Performance        Large   

     Vehicle Style  highway MPG  city mpg  Popularity    MSRP  
2921   Convertible           15        10          86  359990  
3505   Convertible           19        12          86  335000  
5275         Sedan           21        13          86  286750  
5276         Sedan           21        13          86  319400  
5277         Sedan           21        13          86  295850

In [71]:
df3=df3[['Engine HP', 'Engine Cylinders', 'highway MPG']]

In [72]:
df3

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5276       563.0              12.0           21
5277       563.0              12.0           21
5278       563.0              12.0           21
5279       563.0              12.0           20
5280       563.0              12.0           20
5281       563.0              12.0           21
5282       563.0              12.0           21
5283       563.0              12.0           21
5284       563.0              12.0           21
7443       322.0              12.0           15
7444       322.0              12.0           15
7553       453.0              12.0           19
7554       453.0              12.0           19
7555       453.0              12.0           19
7556       453.0              12.0           19
7557       453.0              12.0           19
7558       453.0              12.0           19
7559       453.0              12.0           19
7560       453.0              12.0           19
7561       453.0              12.0           19
7562       453.0              12.0           19
7563       453.0              12.0           19
7564       453.0              12.0           19
9431       322.0              12.0           15
9432       322.0              12.0           15
11448      624.0              12.0           21
11449      624.0              12.0           21
11450      624.0              12.0           21

In [104]:
df3=df3.drop_duplicates()
df3

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [77]:
x = np.array(df3)

In [78]:
x

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [107]:
xt=x.T

In [108]:
xt

array([[325., 563., 563., 563., 322., 453., 624.],
       [  8.,  12.,  12.,  12.,  12.,  12.,  12.],
       [ 15.,  19.,  21.,  20.,  15.,  19.,  21.]])

In [122]:
xtx=xt.dot(x)

In [123]:
xtx

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [124]:
xtx_inv=np.linalg.inv(xtx)

In [125]:
xtx_inv

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [136]:
identity=xtx_inv.dot(xtx)

In [137]:
identity

array([[ 1.00000000e+00, -1.73472348e-18,  8.21391566e-16],
       [ 1.84297022e-13,  1.00000000e+00,  1.39888101e-14],
       [-3.60211860e-13, -1.58206781e-14,  1.00000000e+00]])

In [127]:
np.sum(xtx_inv)

0.032212320677486195

In [128]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])

In [129]:
w=xtx_inv.dot(xt)

In [130]:
w=w*y

In [131]:
w

array([[  -4.86592076,    3.70158161,   -0.44514862,    1.72227877,
          -1.39491731,   -1.98126399,    3.46328627],
       [-190.20088338,  102.98797193,  -75.41225048,    5.90042376,
         229.97158839,   -5.18427392,  -37.03645368],
       [ 251.64624904, -152.77517227,   65.62358801,  -39.58285347,
         -97.39786221,   62.38667397,  -58.24683429]])